trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - app
      - docker/nginx
      - azure/pipelines/app-image.yaml
      - azure/pipelines/templates/stages/app.yaml
      - azure/pipelines/templates/variables/app.yaml
      - azure/pipelines/templates/variables/common.yaml

pr: none

resources:
  pipelines:
    - pipeline: "builder_image"
      source: "Builder Image"
      trigger:
        branches:
          include:
            - master
  repositories:
    - repository: self

variables:
  - template: templates/variables/common.yaml
  - template: templates/variables/app.yaml

stages:
  - template: templates/stages/app.yaml
